# Generated by Django 4.2.1 on 2023-06-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gyventojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=50)),
                ('pavarde', models.CharField(max_length=50)),
                ('buto_namo_nr', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Butas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buto_namo_nr', models.IntegerField()),
                ('gyventojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyventojai.gyventojas')),
            ],
        ),
    ]
