# Generated by Django 4.2.1 on 2023-06-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyventojai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='butas',
            name='plotas',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
